
export const SET_CURRENTSONG = 'SET_CURRENTSONG';

export const SET_PLAYING = 'SET_PLAYING';

export const SET_CURRENTSONG_INFO = 'SET_CURRENTSONG_INFO'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_CURRENTSONG_INDEX = 'SET_CURRENTSONG_INDEX'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_FAVORITE_SONG ='SET_FAVORITE_SONG'

export const SET_FAVORITE_ALBUM = 'SET_FAVORITE_ALBUM'





